# Generated by Django 5.2.17 on 2026-08-25 11:34

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="Заголовок")),
                (
                    "slug",
                    models.SlugField(
                        max_length=160, unique=True, verbose_name="Идентификатор"
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Краткое описание"
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Условия акции"
                    ),
                ),
                (
                    "date_from",
                    models.DateField(
                        blank=True, null=True, verbose_name="Показывать с"
                    ),
                ),
                (
                    "date_to",
                    models.DateField(
                        blank=True, null=True, verbose_name="Показывать до"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Показывать на сайте"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Порядок"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Акция",
                "verbose_name_plural": "Акции",
                "ordering": ["sort_order", "-date_from"],
            },
        ),
    ]
