# Generated by Django 5.2.17 on 2026-09-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_promotionspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='short_description',
            field=models.TextField(blank=True, max_length=255, verbose_name='Краткое описание'),
        ),
    ]
