# Generated by Django 5.2.17 on 2026-10-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_promotion_mobile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='cta_label',
            field=models.CharField(blank=True, max_length=80, verbose_name='Подпись кнопки'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='cta_type',
            field=models.CharField(choices=[('booking', 'Забронировать'), ('request', 'Оставить заявку')], default='booking', max_length=16, verbose_name='Действие кнопки'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликована'),
        ),
    ]
