# Generated by Django 5.2.17 on 2026-10-06 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0006_night_promotion_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='season_end',
            field=models.CharField(blank=True, help_text='Включительно, например 29.09. Окно может переходить через Новый год.', max_length=5, validators=[django.core.validators.RegexValidator('^(0[1-9]|[12]\\d|3[01])\\.(0[1-9]|1[0-2])$', 'Формат ДД.ММ, например 30.04')], verbose_name='по (ДД.ММ)'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='season_start',
            field=models.CharField(blank=True, help_text='Например 30.04. Пусто — показывать круглый год.', max_length=5, validators=[django.core.validators.RegexValidator('^(0[1-9]|[12]\\d|3[01])\\.(0[1-9]|1[0-2])$', 'Формат ДД.ММ, например 30.04')], verbose_name='Каждый год показывать с (ДД.ММ)'),
        ),
    ]
