# Generated by Django 5.2.17 on 2026-08-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("feedback", "Обратная связь"),
                            ("transfer", "Заказ трансфера"),
                            ("certificate", "Подарочный сертификат"),
                            ("house_question", "Вопрос со страницы дома"),
                            ("fallback", "Резервный сценарий бронирования"),
                        ],
                        db_index=True,
                        max_length=24,
                        verbose_name="Тип формы",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Имя")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=32, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("message", models.TextField(blank=True, verbose_name="Сообщение")),
                (
                    "date_from",
                    models.DateField(blank=True, null=True, verbose_name="Дата заезда"),
                ),
                (
                    "date_to",
                    models.DateField(blank=True, null=True, verbose_name="Дата выезда"),
                ),
                (
                    "guests",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Гостей"
                    ),
                ),
                (
                    "source_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Страница отправки"
                    ),
                ),
                (
                    "utm_source",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="utm_source"
                    ),
                ),
                (
                    "utm_medium",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="utm_medium"
                    ),
                ),
                (
                    "utm_campaign",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="utm_campaign"
                    ),
                ),
                (
                    "utm_content",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="utm_content"
                    ),
                ),
                (
                    "utm_term",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="utm_term"
                    ),
                ),
                (
                    "consent_given",
                    models.BooleanField(
                        default=False, verbose_name="Согласие на обработку ПД"
                    ),
                ),
                (
                    "consent_version",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="Версия текста согласия"
                    ),
                ),
                (
                    "consent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата согласия"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_progress", "В работе"),
                            ("done", "Обработана"),
                            ("spam", "Спам"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Проставляется после успешной отправки в Telegram и на email.",
                        null=True,
                        verbose_name="Уведомление отправлено",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Получена"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "ordering": ["-created_at"],
            },
        ),
    ]
