# Generated by Django 5.2.17 on 2026-08-25 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("forms", "0001_initial"),
        ("houses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formsubmission",
            name="house",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to="houses.housepage",
                verbose_name="Дом",
            ),
        ),
    ]
