# Generated by Django 5.2.17 on 2026-10-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='topic',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тема заявки'),
        ),
    ]
