# Generated by Django 5.2.17 on 2026-10-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_formsubmission_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='email_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отправлено на email'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='telegram_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Доставлено в Telegram'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='notified_at',
            field=models.DateTimeField(blank=True, help_text='Последняя успешная отправка хотя бы по одному каналу; статусы каналов ниже.', null=True, verbose_name='Уведомление отправлено'),
        ),
    ]
