# Generated by Django 5.2.17 on 2026-10-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_formsubmission_email_notified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='form_type',
            field=models.CharField(choices=[('feedback', 'Обратная связь'), ('transfer', 'Заказ трансфера'), ('certificate', 'Подарочный сертификат'), ('house_question', 'Вопрос со страницы дома'), ('fallback', 'Резервный сценарий бронирования'), ('group', 'Выезд компании'), ('partner', 'Партнёрство'), ('event', 'Запись на событие')], db_index=True, max_length=24, verbose_name='Тип формы'),
        ),
    ]
