# Generated by Django 5.2.17 on 2026-08-25 11:34

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Название")),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("inside", "В доме"),
                            ("kitchen", "Кухня"),
                            ("bathroom", "Ванная"),
                            ("outside", "На улице"),
                            ("rules", "Условия"),
                        ],
                        default="inside",
                        max_length=16,
                        verbose_name="Группа",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("wifi", "Wi-Fi"),
                            ("parking", "Парковка"),
                            ("kitchen", "Кухня"),
                            ("fridge", "Холодильник"),
                            ("stove", "Плита"),
                            ("microwave", "Микроволновка"),
                            ("kettle", "Чайник"),
                            ("dishes", "Посуда"),
                            ("shower", "Душ"),
                            ("towels", "Полотенца"),
                            ("hairdryer", "Фен"),
                            ("bed", "Спальное место"),
                            ("linen", "Постельное бельё"),
                            ("tv", "Телевизор"),
                            ("heating", "Отопление"),
                            ("conditioner", "Кондиционер"),
                            ("fireplace", "Камин"),
                            ("terrace", "Терраса"),
                            ("bbq", "Мангал"),
                            ("gazebo", "Беседка"),
                            ("sauna", "Баня"),
                            ("pool", "Купель"),
                            ("pets", "Можно с животными"),
                            ("kids", "Можно с детьми"),
                        ],
                        max_length=32,
                        verbose_name="Иконка",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Порядок"
                    ),
                ),
            ],
            options={
                "verbose_name": "Удобство",
                "verbose_name_plural": "Удобства",
                "ordering": ["group", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="В формате +79991234567",
                        max_length=32,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "phone_display",
                    models.CharField(
                        blank=True,
                        help_text="+7 (999) 123-45-67",
                        max_length=32,
                        verbose_name="Телефон для показа",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("telegram_url", models.URLField(blank=True, verbose_name="Telegram")),
                ("whatsapp_url", models.URLField(blank=True, verbose_name="WhatsApp")),
                ("vk_url", models.URLField(blank=True, verbose_name="ВКонтакте")),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, verbose_name="Адрес"),
                ),
                (
                    "yandex_map_url",
                    models.URLField(blank=True, verbose_name="Ссылка на Яндекс.Карты"),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Наименование ИП"
                    ),
                ),
                (
                    "inn",
                    models.CharField(blank=True, max_length=16, verbose_name="ИНН"),
                ),
                (
                    "ogrnip",
                    models.CharField(blank=True, max_length=24, verbose_name="ОГРНИП"),
                ),
                (
                    "legal_address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Юридический адрес"
                    ),
                ),
                (
                    "consent_version",
                    models.CharField(
                        default="1.0",
                        help_text="Меняется при правке текста согласия. Сохраняется вместе с каждой заявкой.",
                        max_length=16,
                        verbose_name="Версия текста согласия",
                    ),
                ),
                (
                    "consent_text",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Текст согласия на обработку ПД"
                    ),
                ),
                (
                    "cookie_text",
                    models.TextField(blank=True, verbose_name="Текст cookie-баннера"),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки сайта",
            },
        ),
    ]
