# Generated by Django 5.2.17 on 2026-08-26 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='directions_page',
            field=models.ForeignKey(blank=True, help_text='Куда ведёт ссылка «Подробный маршрут» из блока на странице дома.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Страница «Как добраться»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='directions_short',
            field=models.TextField(blank=True, help_text='2–3 строки для компактного блока на странице дома. Полный маршрут — на отдельной странице «Как добраться».', verbose_name='Как добраться — краткий текст'),
        ),
    ]
