# Generated by Django 5.2.17 on 2026-08-26 17:17

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sitesettings_directions_page_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaqItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, verbose_name="Вопрос")),
                ("answer", wagtail.fields.RichTextField(verbose_name="Ответ")),
                (
                    "show_on_home",
                    models.BooleanField(
                        default=True, verbose_name="Показывать на главной"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Показывать на сайте"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Порядок"
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос и ответ",
                "verbose_name_plural": "Ответы на вопросы",
                "ordering": ["sort_order", "question"],
            },
        ),
        migrations.CreateModel(
            name="NearbyPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "link_url",
                    models.URLField(
                        blank=True,
                        help_text="Внешний адрес: сайт музея, статья. Пусто — кнопки не будет.",
                        verbose_name="Ссылка «Подробнее»",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Показывать на сайте"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Порядок"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Фото",
                    ),
                ),
            ],
            options={
                "verbose_name": "Место рядом",
                "verbose_name_plural": "Интересное рядом",
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="TerritoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Название")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Краткое описание"
                    ),
                ),
                (
                    "is_large",
                    models.BooleanField(
                        default=False,
                        help_text="Занимает две ячейки в мозаике. Отмечать не больше двух-трёх.",
                        verbose_name="Крупная плитка",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Показывать на сайте"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Порядок"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Фото",
                    ),
                ),
            ],
            options={
                "verbose_name": "Плитка территории",
                "verbose_name_plural": "Наша территория",
                "ordering": ["sort_order", "title"],
            },
        ),
    ]
