# Generated by Django 5.2.17 on 2026-08-27 00:55

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_faqitem_nearbyplace_territoryitem"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaqPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Вступление"
                    ),
                ),
            ],
            options={
                "verbose_name": "Страница «Ответы на вопросы»",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="GalleryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Вступление"
                    ),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(blank=True, verbose_name="Текст"),
                ),
            ],
            options={
                "verbose_name": "Страница «Галерея»",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="NearbyPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Вступление"
                    ),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(blank=True, verbose_name="Текст"),
                ),
            ],
            options={
                "verbose_name": "Страница «Интересное рядом»",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="TerritoryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Вступление"
                    ),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(blank=True, verbose_name="Текст"),
                ),
            ],
            options={
                "verbose_name": "Страница «Территория»",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ContactsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Вступление"
                    ),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Дополнительный текст"
                    ),
                ),
                (
                    "map_embed_url",
                    models.URLField(
                        blank=True, verbose_name="Адрес карты для встраивания"
                    ),
                ),
                (
                    "map_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Превью карты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страница «Контакты»",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Короткое вступление"
                    ),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(blank=True, verbose_name="Текст"),
                ),
                (
                    "show_booking_cta",
                    models.BooleanField(
                        default=True,
                        verbose_name="Показывать кнопку бронирования внизу",
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Фото в шапке страницы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Текстовая страница",
                "verbose_name_plural": "Текстовые страницы",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="DirectionsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Короткое вступление"
                    ),
                ),
                (
                    "car_distance",
                    models.CharField(
                        blank=True,
                        help_text="Например: 100 км от Москвы.",
                        max_length=80,
                        verbose_name="Расстояние на авто",
                    ),
                ),
                (
                    "car_time",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Время в пути на авто"
                    ),
                ),
                (
                    "car_route",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Описание маршрута на авто"
                    ),
                ),
                (
                    "yandex_route_url",
                    models.URLField(
                        blank=True, verbose_name="Ссылка на маршрут в Яндекс.Картах"
                    ),
                ),
                (
                    "transit_route",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="С названиями станций и ориентировочным временем — требование п. 4.2.",
                        verbose_name="Маршрут на электричке или автобусе",
                    ),
                ),
                (
                    "transfer_price",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Стоимость трансфера"
                    ),
                ),
                (
                    "transfer_note",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Порядок заказа трансфера"
                    ),
                ),
                (
                    "map_embed_url",
                    models.URLField(
                        blank=True,
                        help_text="Ссылка «Поделиться → Код для вставки» из Яндекс.Карт, только адрес из src.",
                        verbose_name="Адрес карты для встраивания",
                    ),
                ),
                (
                    "map_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Скриншот карты. Показывается вместо самой карты до клика — так карта не тянет чужие скрипты при загрузке страницы.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Превью карты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страница «Как добраться»",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="GalleryPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Описание фото"
                    ),
                ),
                (
                    "is_large",
                    models.BooleanField(default=False, verbose_name="Крупная плитка"),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="core.gallerypage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото",
                "verbose_name_plural": "Фотографии",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
