# Generated by Django 5.2.17 on 2026-08-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_faqpage_gallerypage_nearbypage_territorypage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="booking_lead_text",
            field=models.TextField(
                blank=True,
                default="Выберите даты и количество гостей — система покажет свободные домики и стоимость. Бронь подтверждается после предоплаты.",
                help_text="2–3 строки, объясняющие, что произойдёт дальше (п. 5.4.3 ТЗ).",
                verbose_name="Подводящий текст над виджетом",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="kontur_hotel_id",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор из личного кабинета Контур.Отеля. Пока поле пустое, все кнопки бронирования показывают резервную форму заявки — сайт остаётся рабочим.",
                max_length=64,
                verbose_name="hotelId Контур.Отеля",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="yandex_metrika_id",
            field=models.CharField(
                blank=True,
                help_text="Только цифры. Пока пусто — цели бронирования не отправляются.",
                max_length=16,
                verbose_name="Номер счётчика Яндекс.Метрики",
            ),
        ),
    ]
