# Generated by Django 5.2.17 on 2026-08-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_sitesettings_booking_lead_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="instagram_url",
            field=models.URLField(blank=True, verbose_name="Instagram"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="tiktok_url",
            field=models.URLField(blank=True, verbose_name="TikTok"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="work_hours",
            field=models.CharField(
                blank=True,
                help_text="Например: 10:00 — 22:00",
                max_length=64,
                verbose_name="Часы работы",
            ),
        ),
    ]
