# Generated by Django 5.2.17 on 2026-09-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_sitesettings_instagram_url_sitesettings_tiktok_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="territoryitem",
            name="spacer_before",
            field=models.BooleanField(
                default=False,
                help_text="В макете мозаика намеренно разрежена — две ячейки оставлены пустыми. Отметьте, чтобы сдвинуть этот блок на одну ячейку вправо.",
                verbose_name="Пустая ячейка перед этим блоком",
            ),
        ),
        migrations.AlterField(
            model_name="territoryitem",
            name="is_large",
            field=models.BooleanField(
                default=False,
                help_text="Не используется в блоке «Наша территория»: по замерам макета все плитки там строго квадратные, 295×295.",
                verbose_name="Крупная плитка",
            ),
        ),
    ]
