# Generated by Django 5.2.17 on 2026-09-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_amenitygroup_amenity_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='guests_adults_note',
            field=models.CharField(blank=True, default='Возраст от 7 лет', max_length=120, verbose_name='Подпись у счётчика «Взрослые»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='guests_children_note',
            field=models.CharField(blank=True, default='Бесплатно до 7 лет', max_length=120, verbose_name='Подпись у счётчика «Дети»'),
        ),
    ]
