# Generated by Django 5.2.17 on 2026-09-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_amenity_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenitygroup',
            name='column',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Первая'), (2, 'Вторая'), (3, 'Третья')], default=1, verbose_name='Колонка в развёрнутом описании'),
        ),
    ]
