# Generated by Django 5.2.17 on 2026-09-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_amenitygroup_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='in_list',
            field=models.BooleanField(default=True, help_text='Снимите, если плитка дублирует пункт списка другим названием.', verbose_name='Показывать в развёрнутом описании'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Короткий список главного над развёрнутым описанием.', verbose_name='Показывать плиткой в «Удобствах»'),
        ),
    ]
