# Generated by Django 5.2.17 on 2026-09-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_amenity_in_list_alter_amenity_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='featured_order',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Порядок среди плиток'),
        ),
    ]
