# Generated by Django 5.2.17 on 2026-09-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_amenity_featured_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='territoryitem',
            name='link_url',
            field=models.URLField(blank=True, help_text='Адрес страницы карточки. Пусто — кнопка не показывается.', verbose_name='Ссылка «Подробнее»'),
        ),
    ]
