# Generated by Django 5.2.17 on 2026-09-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_faq_design_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='child_free_max_age',
            field=models.PositiveSmallIntegerField(default=7, help_text='Ребёнок этого возраста и младше не оплачивается. Старше — считается обычным гостем.', verbose_name='Дети бесплатно до возраста включительно'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='extra_guest_fee',
            field=models.PositiveIntegerField(default=1000, help_text='За каждого платного гостя сверх «Гостей в базовой цене».', verbose_name='Доплата за гостя сверх базы, ₽/сутки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='guests_included',
            field=models.PositiveSmallIntegerField(default=2, help_text='Сколько платных гостей входит в цену домика без доплаты.', verbose_name='Гостей в базовой цене'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pet_large_fee',
            field=models.PositiveIntegerField(default=1500, verbose_name='Доплата за питомца выше 45 см, ₽/сутки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pet_small_fee',
            field=models.PositiveIntegerField(default=1000, verbose_name='Доплата за питомца до 45 см, ₽/сутки'),
        ),
    ]
