# Generated by Django 5.2.17 on 2026-10-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_sitesettings_child_free_max_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='booking_show_hourly',
            field=models.BooleanField(default=True, verbose_name='Показывать баню и беседки в окне бронирования'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='form_reply_time',
            field=models.CharField(blank=True, help_text='например: в течение 30 минут с 9:00 до 21:00', max_length=160, verbose_name='Срок ответа на заявку'),
        ),
    ]
