# Generated by Django 5.2.17 on 2026-10-03 10:58

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_archivephotoimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='about_content',
            field=wagtail.fields.StreamField([('content', 38)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок первого экрана'}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Текст первого экрана'}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.ListBlock', (2,), {'label': 'Вступление: абзацы'}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'История: начало'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'История: подводка к названию'}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'История: название'}), 7: ('wagtail.blocks.TextBlock', (), {'label': 'История: продолжение'}), 8: ('wagtail.blocks.TextBlock', (), {'label': 'История: завершение'}), 9: ('wagtail.blocks.TextBlock', (), {'label': 'Девиз'}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фотография', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Описание фотографии', 'required': False}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('aerial', 'aerial'), ('story-moss', 'story-moss'), ('story-terrace', 'story-terrace'), ('story-season', 'story-season'), ('pillar-farm', 'pillar-farm'), ('pillar-slow', 'pillar-slow'), ('pillar-comfort', 'pillar-comfort'), ('value-journey', 'value-journey'), ('value-pleasure', 'value-pleasure'), ('value-trust', 'value-trust'), ('value-friendship', 'value-friendship'), ('value-sharing', 'value-sharing'), ('value-care', 'value-care'), ('pet-snezhka', 'pet-snezhka'), ('pet-dymok', 'pet-dymok'), ('diary-holidays', 'diary-holidays'), ('diary-ayka', 'diary-ayka'), ('diary-car', 'diary-car')], 'label': 'Кадрирование исходного макета', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('image', 10), ('alt', 11), ('crop', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {'label': 'Фото истории (4 позиции)', 'max_num': 4, 'min_num': 4}), 15: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок столпов'}), 16: ('wagtail.blocks.TextBlock', (), {'label': 'Заголовок (переносы строк сохраняются)'}), 17: ('wagtail.blocks.TextBlock', (), {'label': 'Подводка', 'required': False}), 18: ('wagtail.blocks.TextBlock', (), {'label': 'Текст', 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('image', 10), ('alt', 11), ('crop', 12), ('title', 16), ('lead', 17), ('text', 18)]], {}), 20: ('wagtail.blocks.ListBlock', (19,), {'label': 'Три столпа', 'max_num': 3, 'min_num': 3}), 21: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок ценностей'}), 22: ('wagtail.blocks.ListBlock', (19,), {'label': 'Ценности', 'min_num': 1}), 23: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок питомцев'}), 24: ('wagtail.blocks.TextBlock', (), {'label': 'Текст о питомцах'}), 25: ('wagtail.blocks.CharBlock', (), {'label': 'Имя'}), 26: ('wagtail.blocks.TextBlock', (), {'label': 'Подпись'}), 27: ('wagtail.blocks.TextBlock', (), {'label': 'Подробности'}), 28: ('wagtail.blocks.StructBlock', [[('image', 10), ('alt', 11), ('crop', 12), ('name', 25), ('copy', 26), ('details', 27)]], {}), 29: ('wagtail.blocks.ListBlock', (28,), {'label': 'Питомцы'}), 30: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок дневника'}), 31: ('wagtail.blocks.TextBlock', (), {'label': 'Текст дневника'}), 32: ('wagtail.blocks.TextBlock', (), {'label': 'Заголовок'}), 33: ('wagtail.blocks.URLBlock', (), {'label': 'Ссылка на запись', 'required': False}), 34: ('wagtail.blocks.StructBlock', [[('image', 10), ('alt', 11), ('crop', 12), ('title', 32), ('url', 33)]], {}), 35: ('wagtail.blocks.ListBlock', (34,), {'label': 'Записи дневника'}), 36: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок карты'}), 37: ('wagtail.blocks.TextBlock', (), {'label': 'Текст карты'}), 38: ('wagtail.blocks.StructBlock', [[('hero_title', 0), ('hero_text', 1), ('intro', 3), ('story_first', 4), ('story_name_lead', 5), ('story_name', 6), ('story_name_text', 7), ('story_last', 8), ('motto', 9), ('history_photos', 14), ('pillars_title', 15), ('pillars', 20), ('values_title', 21), ('values', 22), ('pets_title', 23), ('pets_text', 24), ('pets', 29), ('diary_title', 30), ('diary_text', 31), ('diary', 35), ('map_title', 36), ('map_text', 37)]], {})}, verbose_name='Содержимое «О нас»'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='about_initialized',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='legal_body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('list', 3), ('table', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок раздела'}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Абзац (точный текст документа)'}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.ListBlock', (2,), {'label': 'Список (исходная нумерация/маркеры)'}), 4: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица', 'table_options': {'renderer': 'text'}})}, verbose_name='Полный текст документа'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='legal_source_sha256',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
