# Generated by Django 5.2.17 on 2026-10-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_contentpage_about_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, max_length=120, unique=True)),
                ('label', models.CharField(editable=False, max_length=255, verbose_name='Где используется')),
                ('text', models.TextField(blank=True, verbose_name='Текст (без HTML и стилей)')),
            ],
            options={
                'verbose_name': 'Подпись интерфейса',
                'verbose_name_plural': 'Подписи интерфейса',
                'ordering': ['label'],
            },
        ),
    ]
