# Generated by Django 5.2.17 on 2026-10-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_interfacetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='booking_show_search_fields',
            field=models.BooleanField(default=False, help_text='Главная и «Размещение». Выбор в самом виджете остаётся доступным.', verbose_name='Показывать даты и гостей над кнопкой бронирования'),
        ),
    ]
