# Generated by Django 5.2.17 on 2026-10-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_directions_faq_facts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='in_progress',
            field=models.BooleanField(default=False, help_text='Показать плашку «Раздел дополняется» и закрыть страницу от поисковиков, пока она не готова.', verbose_name='Раздел дополняется'),
        ),
        migrations.AddField(
            model_name='directionspage',
            name='in_progress',
            field=models.BooleanField(default=False, help_text='Показать плашку «Раздел дополняется» и закрыть страницу от поисковиков, пока она не готова.', verbose_name='Раздел дополняется'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='in_progress',
            field=models.BooleanField(default=False, help_text='Показать плашку «Раздел дополняется» и закрыть страницу от поисковиков, пока она не готова.', verbose_name='Раздел дополняется'),
        ),
        migrations.AddField(
            model_name='nearbypage',
            name='in_progress',
            field=models.BooleanField(default=False, help_text='Показать плашку «Раздел дополняется» и закрыть страницу от поисковиков, пока она не готова.', verbose_name='Раздел дополняется'),
        ),
        migrations.AddField(
            model_name='territorypage',
            name='in_progress',
            field=models.BooleanField(default=False, help_text='Показать плашку «Раздел дополняется» и закрыть страницу от поисковиков, пока она не готова.', verbose_name='Раздел дополняется'),
        ),
    ]
