# Generated by Django 5.2.17 on 2026-10-07 07:40

from django.db import migrations, models

# Администратор из описания канала t.me/best_season_bs: «По всем вопросам: @BestSeason_adm».
ADMIN_CHAT = "https://t.me/BestSeason_adm"


def fill_chat(apps, schema_editor):
    SiteSettings = apps.get_model("core", "SiteSettings")
    SiteSettings.objects.using(schema_editor.connection.alias).filter(telegram_chat_url="").update(telegram_chat_url=ADMIN_CHAT)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_gallery_archive_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_chat_url',
            field=models.URLField(blank=True, help_text='Чат администратора, например https://t.me/BestSeason_adm. Пусто — используется ссылка Telegram выше.', verbose_name='Telegram для сообщений'),
        ),
        migrations.RunPython(fill_chat, migrations.RunPython.noop),
    ]
