# Generated by Django 5.2.17 on 2026-10-07 07:42

from django.db import migrations, models

# Факты из ответа FAQ «Как добраться до глэмпинга?»; заполняем только пустые поля.
TRAIN = {
    "train_station": "Тарусская",
    "train_time": "1,2–2,5 ч",
    "train_price": "от 400 ₽",
    "train_schedule_url": "https://www.tutu.ru/rasp.php?st1=20000&st2=43806",
}


def fill_train(apps, schema_editor):
    DirectionsPage = apps.get_model("core", "DirectionsPage")
    Revision = apps.get_model("wagtailcore", "Revision")
    alias = schema_editor.connection.alias
    for page in DirectionsPage.objects.using(alias).iterator():
        DirectionsPage.objects.using(alias).filter(pk=page.pk).update(**TRAIN)
        revision = Revision.objects.using(alias).filter(pk=page.latest_revision_id).first()
        if revision and isinstance(revision.content, dict):
            content = dict(revision.content)
            content.update({k: v for k, v in TRAIN.items() if not content.get(k)})
            Revision.objects.using(alias).filter(pk=revision.pk).update(content=content)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_telegram_chat_url'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='directionspage',
            name='train_price',
            field=models.CharField(blank=True, max_length=80, verbose_name='Стоимость электрички'),
        ),
        migrations.AddField(
            model_name='directionspage',
            name='train_schedule_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на расписание'),
        ),
        migrations.AddField(
            model_name='directionspage',
            name='train_station',
            field=models.CharField(blank=True, help_text='Например: Тарусская.', max_length=80, verbose_name='Станция'),
        ),
        migrations.AddField(
            model_name='directionspage',
            name='train_time',
            field=models.CharField(blank=True, max_length=80, verbose_name='Время в пути на электричке'),
        ),
        migrations.RunPython(fill_train, migrations.RunPython.noop),
    ]
