# Generated by Django 5.2.17 on 2026-10-07 07:43

from django.db import migrations, models

# Темы для текущих вопросов сайта; редакторская тема не перезаписывается.
TOPICS = {
    "booking": ("Какие условия бронирования", "Какая нужна предоплата", "Что если планы изменятся",
                "Можно ли арендовать домик на месяц"),
    "checkin": ("Во сколько заезд и выезд", "Как проходит заселение"),
    "houses": ("Сколько человек может жить", "Стабильная ли связь", "Есть ли завтраки", "Можно ли слушать музыку"),
    "pets": ("Можно ли кормить животных", "Можно ли с животными"),
    "road": ("Как добраться до глэмпинга",),
    "promo": ("Действует ли скидка", "Суммируются ли скидки", "Действуют ли акции", "Есть ли подарочные сертификаты"),
}


def fill_topics(apps, schema_editor):
    FaqItem = apps.get_model("core", "FaqItem")
    items = FaqItem.objects.using(schema_editor.connection.alias)
    for topic, starts in TOPICS.items():
        for start in starts:
            items.filter(topic="", question__startswith=start).update(topic=topic)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_directions_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqitem',
            name='topic',
            field=models.CharField(blank=True, choices=[('booking', 'Бронь и оплата'), ('checkin', 'Заезд'), ('houses', 'Домики'), ('pets', 'Животные'), ('road', 'Дорога'), ('promo', 'Акции')], help_text='Чип-фильтр на странице «Ответы на вопросы».', max_length=16, verbose_name='Тема'),
        ),
        migrations.RunPython(fill_topics, migrations.RunPython.noop),
    ]
