# Generated by Django 5.2.17 on 2026-10-07 07:50

from django.db import migrations, models

# На главной «Подробнее» ведёт на эту страницу, поэтому link_url первых трёх
# мест не трогаем: ссылки на источники — только у новых мест.
# Источники: карточки сайта (расстояния), пост Telegram 11.10.2025 (экскурсии
# к Конюхову), 21.06.2026 (пляж), VK, август 2026 (корт), UNWTO 2021 (Бёхово).
PLACES = {
    'Усадьба': {"distance_label": "3 км", "tags": "с детьми, круглый год"},
    'деревня Ф. Конюхова': {"distance_label": "6 км", "tags": "с детьми, круглый год"},
    'деревня "Бёхово"': {"distance_label": "5 км", "tags": "прогулка, круглый год"},
}
NEW_PLACES = [
    {"title": "Серпуховские Мальдивы", "sort_order": 40, "distance_label": "≈30 мин на машине",
     "seasons": "summer", "tags": "пляж, вход свободный",
     "description": "Пляж на Оке с мелким светлым песком: лежаки, беседки, детские и спортивные площадки, "
                    "смотровые и закаты, ради которых стоит задержаться до вечера.",
     "link_url": "https://t.me/best_season_bs/127",
     "route_url": "https://yandex.ru/maps/org/plyazh_na_smotrovoy/216265396468"},
    {"title": "Теннисный корт", "sort_order": 50, "distance_label": "рядом",
     "seasons": "spring summer autumn", "tags": "спорт",
     "description": "Рядом с глэмпингом есть корт — доехать проще, чем до ближайшего светофора в городе. "
                    "Как забронировать время, подскажет администратор; ракетки берите с собой.",
     "link_url": "https://vk.ru/glamping_bestseason"},
]
FACTS = chr(10).join([
    "44 из 170 | деревень мира в списке UNWTO 2021, среди них Бёхово",
    "ср–вс | усадьба Поленово открыта с 11:00 до 17:00",
])
DAY_ROUTE = chr(10).join([
    "11:00 | Усадьба Поленово | дом художника и парк над Окой",
    "13:00 | Деревня Фёдора Конюхова | мастерская с артефактами экспедиций",
    "16:00 | Церковь Троицы в Бёхово | построена по эскизам Поленова",
    "19:00 | Костёр в «Лучшем сезоне» | ужин на террасе и звёзды",
])


def fill(apps, schema_editor):
    alias = schema_editor.connection.alias
    NearbyPlace = apps.get_model("core", "NearbyPlace")
    NearbyPage = apps.get_model("core", "NearbyPage")
    Revision = apps.get_model("wagtailcore", "Revision")
    for start, values in PLACES.items():
        for place in NearbyPlace.objects.using(alias).filter(title__startswith=start):
            changed = {k: v for k, v in values.items() if not getattr(place, k)}
            if changed:
                NearbyPlace.objects.using(alias).filter(pk=place.pk).update(**changed)
    for values in NEW_PLACES:
        if not NearbyPlace.objects.using(alias).filter(title=values["title"]).exists():
            NearbyPlace.objects.using(alias).create(is_published=True, **values)
    for page in NearbyPage.objects.using(alias).all():
        changed = {k: v for k, v in (("facts", FACTS), ("day_route", DAY_ROUTE)) if not getattr(page, k)}
        if changed:
            NearbyPage.objects.using(alias).filter(pk=page.pk).update(**changed)
        revision = Revision.objects.using(alias).filter(pk=page.latest_revision_id).first()
        if revision and isinstance(revision.content, dict):
            content = dict(revision.content)
            content.update({k: v for k, v in (("facts", FACTS), ("day_route", DAY_ROUTE)) if not content.get(k)})
            Revision.objects.using(alias).filter(pk=revision.pk).update(content=content)


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('core', '0030_faq_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbypage',
            name='day_route',
            field=models.TextField(blank=True, help_text='По строке на точку: время | место | одна строка о нём.', verbose_name='Маршрут на день'),
        ),
        migrations.AddField(
            model_name='nearbypage',
            name='facts',
            field=models.TextField(blank=True, help_text='По строке на карточку: значение | подпись. Например: 44 из 170 | деревень мира в списке ООН.', verbose_name='Факты'),
        ),
        migrations.AddField(
            model_name='nearbyplace',
            name='distance_label',
            field=models.CharField(blank=True, help_text='Например: 3 км или ≈30 мин на машине.', max_length=40, verbose_name='Расстояние'),
        ),
        migrations.AddField(
            model_name='nearbyplace',
            name='route_url',
            field=models.URLField(blank=True, help_text='Пусто — маршрут в Яндекс Картах строится по названию.', verbose_name='Маршрут'),
        ),
        migrations.AddField(
            model_name='nearbyplace',
            name='seasons',
            field=models.CharField(blank=True, help_text='Через пробел: spring summer autumn winter. Пусто — круглый год.', max_length=40, verbose_name='Сезоны'),
        ),
        migrations.AddField(
            model_name='nearbyplace',
            name='tags',
            field=models.CharField(blank=True, help_text='Через запятую, например: с детьми.', max_length=120, verbose_name='Метки'),
        ),
        migrations.RunPython(fill, migrations.RunPython.noop),
    ]
