# Generated by Django 5.2.17 on 2026-10-07 07:55
"""Территория: группы карточек для чипов и вступление вместо пометки сида.

Тексты — из фактов сайта («О нас», главная). Меняется только пустое поле
или текст с пометкой «Текст ожидается от заказчика»; правки редактора целы.
"""
from django.db import migrations, models

GROUPS = {
    "kids": ("Контактная ферма", "Батут", "Спортивные игры"),
    "warm": ("Русская баня", "Финская сауна", "Костровая зона"),
    "water": ("Река", "Большая беседка", "Мастер-классы", "Фотосессии"),
}
MARKER = "Текст ожидается от заказчика"
BODY = (
    "<p>Глэмпинг стоит на краю леса: с трёх сторон его обступают деревья, вдоль территории течёт "
    "небольшая речка Скнижка. От домиков тропинки ведут к бане, большой беседке, костровой зоне "
    "и собственной контактной ферме.</p>"
    "<p>Ниже — всё, что есть на территории. У бани и беседки сразу видна цена, а финская сауна "
    "входит в бронь Домика №1.</p>"
)


def fill(apps, schema_editor):
    alias = schema_editor.connection.alias
    TerritoryItem = apps.get_model("core", "TerritoryItem")
    TerritoryPage = apps.get_model("core", "TerritoryPage")
    Revision = apps.get_model("wagtailcore", "Revision")
    for group, starts in GROUPS.items():
        for start in starts:
            TerritoryItem.objects.using(alias).filter(group="", title__startswith=start).update(group=group)
    for page in TerritoryPage.objects.using(alias).all():
        if not page.body or MARKER in page.body:
            TerritoryPage.objects.using(alias).filter(pk=page.pk).update(body=BODY)
        revision = Revision.objects.using(alias).filter(pk=page.latest_revision_id).first()
        if revision and isinstance(revision.content, dict):
            body = revision.content.get("body") or ""
            if not body or MARKER in body:
                Revision.objects.using(alias).filter(pk=revision.pk).update(content={**revision.content, "body": BODY})


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_nearby_details'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='territoryitem',
            name='group',
            field=models.CharField(blank=True, choices=[('kids', 'С детьми и животными'), ('warm', 'Тепло и пар'), ('water', 'Вода и события')], max_length=8, verbose_name='Группа на странице «Территория»'),
        ),
        migrations.RunPython(fill, migrations.RunPython.noop),
    ]
