# Generated by Django 5.2.17 on 2026-10-07 07:59

from django.db import migrations, models

# Разделы ждут ответов команды (даты событий, условия партнёров, тариф круглый год):
# страница живая, но с плашкой «Раздел дополняется» (docs/dop-stranicy/README.md).
IN_PROGRESS = ("meropriyatiya", "partneram", "vyezdy-kompaniy")


def mark_in_progress(apps, schema_editor):
    alias = schema_editor.connection.alias
    ContentPage = apps.get_model("core", "ContentPage")
    Revision = apps.get_model("wagtailcore", "Revision")
    for page in ContentPage.objects.using(alias).filter(slug__in=IN_PROGRESS):
        ContentPage.objects.using(alias).filter(pk=page.pk).update(in_progress=True)
        revision = Revision.objects.using(alias).filter(pk=page.latest_revision_id).first()
        if revision and isinstance(revision.content, dict):
            Revision.objects.using(alias).filter(pk=revision.pk).update(content={**revision.content, "in_progress": True})


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('core', '0032_territory_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('published_at', models.DateTimeField()),
                ('text', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Пост канала',
                'verbose_name_plural': 'Посты канала',
                'ordering': ['-published_at'],
            },
        ),
        migrations.RunPython(mark_in_progress, migrations.RunPython.noop),
    ]
