# Generated by Django 5.2.17 on 2026-10-07 08:04

from django.db import migrations, models

# Разметка 18 фото архива по самим снимкам (07.10): что на фото, сезон, подпись.
# Пустой сезон — по кадру не определить (печь, ночной костёр).
PHOTOS = {
    "0d84e92d4a8a": ("animals", "summer", "Кот в зарослях у домиков"),
    "1b1a569b9028": ("animals", "summer", "Колли на лужайке"),
    "214db492a896": ("animals", "summer", "Колли у реки"),
    "27cd570709ed": ("animals", "summer", "Обитатель контактной фермы"),
    "281de0fa11e1": ("animals", "summer", "Ягнёнок на траве"),
    "2c33d8bc91f0": ("animals", "summer", "Кошка на террасе"),
    "59e3b806265c": ("territory", "summer", "Речка Скнижка под ивами"),
    "6e018e4d455a": ("animals", "summer", "Белая коза у домика"),
    "86976b51cd1e": ("animals", "summer", "Колли в реке"),
    "ab386e650ca6": ("territory", "summer", "Полевые цветы и подвесное кресло"),
    "bc63e896035d": ("territory", "summer", "Фотосессия на территории"),
    "c4ab1a4dabb1": ("territory", "", "Огонь в печи беседки"),
    "d3c8de6fed65": ("territory", "summer", "Бадминтон на поляне"),
    "d41ac81e6204": ("territory", "summer", "Подвесные кресла на террасе"),
    "ece2f0a68970": ("animals", "summer", "Колли у воды"),
    "f4eec7b48ced": ("territory", "summer", "Прогулка с зонтом по поляне"),
    "f8df1d7dad76": ("territory", "summer", "Фотосессия на поляне"),
    "fb4c7b48c4fd": ("territory", "", "Ночной костёр"),
}


def fill(apps, schema_editor):
    GalleryPhoto = apps.get_model("core", "GalleryPhoto")
    for photo in GalleryPhoto.objects.using(schema_editor.connection.alias).select_related("image"):
        key = photo.image.title.rsplit("/", 1)[-1] if photo.image else ""
        if key not in PHOTOS:
            continue
        category, season, alt = PHOTOS[key]
        changed = {}
        if not photo.category:
            changed["category"] = category
        if not photo.season and season:
            changed["season"] = season
        if not photo.alt:
            changed["alt"] = alt
        if changed:
            GalleryPhoto.objects.using(schema_editor.connection.alias).filter(pk=photo.pk).update(**changed)
    # Ревизия хранит свою копию фото: без разметки следующая публикация из админки её сотрёт.
    GalleryPage = apps.get_model("core", "GalleryPage")
    Revision = apps.get_model("wagtailcore", "Revision")
    alias = schema_editor.connection.alias
    for page in GalleryPage.objects.using(alias).all():
        revision = Revision.objects.using(alias).filter(pk=page.latest_revision_id).first()
        if not (revision and isinstance(revision.content, dict) and revision.content.get("photos")):
            continue
        live = {photo.pk: photo for photo in GalleryPhoto.objects.using(alias).filter(page=page)}
        photos = []
        for item in revision.content["photos"]:
            photo = live.get(item.get("pk"))
            if photo:
                item = {**item, "category": item.get("category") or photo.category,
                        "season": item.get("season") or photo.season, "alt": item.get("alt") or photo.alt}
            photos.append(item)
        Revision.objects.using(alias).filter(pk=revision.pk).update(content={**revision.content, "photos": photos})


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_dop_pages'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='category',
            field=models.CharField(blank=True, choices=[('houses', 'Домики'), ('territory', 'Территория'), ('animals', 'Животные'), ('around', 'Окрестности')], max_length=12, verbose_name='Что на фото'),
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='season',
            field=models.CharField(blank=True, choices=[('spring', 'Весна'), ('summer', 'Лето'), ('autumn', 'Осень'), ('winter', 'Зима')], max_length=8, verbose_name='Сезон'),
        ),
        migrations.RunPython(fill, migrations.RunPython.noop),
    ]
