# Generated by Django 5.2.17 on 2026-10-07 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_gallery_categories'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('end_date', models.DateField(blank=True, help_text='Для событий на несколько дней.', null=True, verbose_name='Дата окончания')),
                ('time_label', models.CharField(blank=True, help_text='Например: 13:00 или весь день.', max_length=40, verbose_name='Время')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(blank=True, help_text='Пусто — «стоимость по запросу».', null=True, verbose_name='Цена, ₽')),
                ('places', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Мест')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['date'],
            },
        ),
    ]
