# Generated by Django 5.2.17 on 2026-10-07 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_event'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('territory-walk', 'Территория: прогулка по глэмпингу'), ('directions-road', 'Как добраться: последний километр и въезд'), ('gallery-morning-1', 'Галерея: «Утреннее» 1'), ('gallery-morning-2', 'Галерея: «Утреннее» 2'), ('gallery-morning-3', 'Галерея: «Утреннее» 3'), ('group-evening', 'Выезды компаний: вечер в полном составе'), ('scenario-day', 'Чем заняться: один день в «Лучшем сезоне»')], max_length=32, unique=True, verbose_name='Место на сайте')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Подпись')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtaildocs.document', verbose_name='Файл видео (MP4)')),
                ('poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео на сайте',
            },
        ),
    ]
