# Generated by Django 5.2.17 on 2026-08-25 11:34

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Вступительный текст"
                    ),
                ),
            ],
            options={
                "verbose_name": "Раздел «Наши домики»",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="HousePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "pms_name",
                    models.CharField(
                        blank=True,
                        help_text="Точно как заведено в PMS Контур.Отеля. Выводится подписью у кнопки бронирования.",
                        max_length=255,
                        verbose_name="Название категории в Контуре",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="Одна строка под названием на первом экране и в карточке дома.",
                        max_length=255,
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(blank=True, verbose_name="Описание"),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="Вместимость, чел."
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=6,
                        null=True,
                        verbose_name="Площадь, м²",
                    ),
                ),
                (
                    "highlight",
                    models.CharField(
                        blank=True,
                        help_text="Коротко: «с камином», «с панорамным окном». Показывается в характеристиках.",
                        max_length=120,
                        verbose_name="Особенность",
                    ),
                ),
                (
                    "price_from",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Справочно для витрины. Итоговый расчёт — всегда в виджете Контура.",
                        null=True,
                        verbose_name="Цена от, ₽/сутки",
                    ),
                ),
                (
                    "sort_order_index",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Порядок в списке"
                    ),
                ),
                (
                    "amenities",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="core.amenity", verbose_name="Что входит"
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Фото первого экрана",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страница дома",
                "verbose_name_plural": "Страницы домов",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="HouseGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Используется как alt. Пустая подпись — alt соберётся из названия дома.",
                        max_length=200,
                        verbose_name="Подпись",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="houses.housepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото галереи",
                "verbose_name_plural": "Фото галереи",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
