# Generated by Django 5.2.17 on 2026-09-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0002_houseindexpage_hero_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="houseindexpage",
            name="heading",
            field=models.CharField(
                blank=True,
                help_text="Если пусто — берётся название страницы",
                max_length=120,
                verbose_name="Заголовок на странице",
            ),
        ),
    ]
