# Generated by Django 5.2.17 on 2026-09-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0003_houseindexpage_heading"),
    ]

    operations = [
        migrations.AddField(
            model_name="houseindexpage",
            name="services_intro",
            field=models.TextField(
                blank=True,
                help_text="Перенос строки задаётся переводом строки",
                verbose_name="Подпись под заголовком «Доп услуги»",
            ),
        ),
    ]
