# Generated by Django 5.2.17 on 2026-09-06 15:50

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_houseindexpage_services_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='housepage',
            name='layout_note',
            field=models.CharField(blank=True, help_text='Коротко: «Свободная планировка». Строка в карточке вместимости.', max_length=80, verbose_name='Планировка'),
        ),
        migrations.AddField(
            model_name='housepage',
            name='max_adults',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Максимум взрослых'),
        ),
        migrations.AddField(
            model_name='housepage',
            name='max_children',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Максимум детей'),
        ),
        migrations.AddField(
            model_name='housepage',
            name='max_pets',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Максимум питомцев'),
        ),
        migrations.AddField(
            model_name='housepage',
            name='pet_fee',
            field=models.PositiveIntegerField(default=0, help_text='За одного питомца за всё проживание. Выводится подсказкой у счётчика.', verbose_name='Доплата за питомца, ₽'),
        ),
        migrations.AddField(
            model_name='housepage',
            name='price_per_night',
            field=models.PositiveIntegerField(blank=True, help_text='Базовая цена расчёта. Если пусто — берётся «Цена от».', null=True, verbose_name='Цена за ночь, ₽'),
        ),
        migrations.AlterField(
            model_name='housepage',
            name='price_from',
            field=models.PositiveIntegerField(blank=True, help_text='Справочно для витрины: лента цены на карточке дома.', null=True, verbose_name='Цена от, ₽/сутки'),
        ),
        migrations.CreateModel(
            name='HousePriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('date_from', models.DateField(verbose_name='С')),
                ('date_to', models.DateField(help_text='Включительно.', verbose_name='По')),
                ('price_per_night', models.PositiveIntegerField(verbose_name='Цена за ночь, ₽')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='houses.housepage')),
            ],
            options={
                'verbose_name': 'Сезонная цена',
                'verbose_name_plural': 'Сезонные цены',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseSleepingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=80, verbose_name='Название')),
                ('icon', models.CharField(blank=True, choices=[('wifi', 'Wi-Fi'), ('parking', 'Парковка'), ('kitchen', 'Кухня'), ('fridge', 'Холодильник'), ('stove', 'Плита'), ('microwave', 'Микроволновка'), ('kettle', 'Чайник'), ('dishes', 'Посуда'), ('shower', 'Душ'), ('towels', 'Полотенца'), ('hairdryer', 'Фен'), ('bed', 'Спальное место'), ('linen', 'Постельное бельё'), ('tv', 'Телевизор'), ('heating', 'Отопление'), ('conditioner', 'Кондиционер'), ('fireplace', 'Камин'), ('terrace', 'Терраса'), ('bbq', 'Мангал'), ('gazebo', 'Беседка'), ('sauna', 'Баня'), ('pool', 'Купель'), ('pets', 'Можно с животными'), ('kids', 'Можно с детьми'), ('capacity', 'Вместимость'), ('guest', 'Гость'), ('area', 'Площадь'), ('layout', 'Планировка'), ('sofa_bed', 'Диван-кровать'), ('bunk_bed', 'Двухэтажная кровать'), ('moon', 'Ночи')], max_length=32, verbose_name='Иконка')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleeping_places', to='houses.housepage')),
            ],
            options={
                'verbose_name': 'Спальное место',
                'verbose_name_plural': 'Спальные места',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
