# Generated by Django 5.2.17 on 2026-09-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_housepage_layout_note_housepage_max_adults_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housesleepingplace',
            name='icon',
            field=models.CharField(blank=True, choices=[('wifi', 'Wi-Fi'), ('parking', 'Парковка'), ('kitchen', 'Кухня'), ('fridge', 'Холодильник'), ('stove', 'Плита'), ('microwave', 'Микроволновка'), ('kettle', 'Чайник'), ('dishes', 'Посуда'), ('shower', 'Душ'), ('towels', 'Полотенца'), ('hairdryer', 'Фен'), ('bed', 'Спальное место'), ('linen', 'Постельное бельё'), ('tv', 'Телевизор'), ('heating', 'Отопление'), ('conditioner', 'Кондиционер'), ('fireplace', 'Камин'), ('terrace', 'Терраса'), ('bbq', 'Мангал'), ('gazebo', 'Беседка'), ('sauna', 'Баня'), ('pool', 'Купель'), ('pets', 'Можно с животными'), ('kids', 'Можно с детьми'), ('capacity', 'Вместимость'), ('guest', 'Гость'), ('calendar', 'Календарь'), ('camera', 'Фотоаппарат'), ('area', 'Площадь'), ('layout', 'Планировка'), ('sofa_bed', 'Диван-кровать'), ('bunk_bed', 'Двухэтажная кровать'), ('moon', 'Ночи')], max_length=32, verbose_name='Иконка'),
        ),
    ]
