# Generated by Django 5.2.17 on 2026-09-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_first_house_description_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housepage',
            name='pet_fee',
            field=models.PositiveIntegerField(default=0, help_text='Только для подписи у счётчика. Ставки расчёта общие для всех домиков и заданы в настройках сайта.', verbose_name='Доплата за питомца, ₽'),
        ),
    ]
