# Generated by Django 5.2.17 on 2026-08-25 11:34

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(
                        max_length=120, unique=True, verbose_name="Идентификатор"
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Краткое описание"
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(blank=True, verbose_name="Описание"),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Цена, ₽"
                    ),
                ),
                (
                    "price_unit",
                    models.CharField(
                        choices=[
                            ("hour", "за час"),
                            ("day", "за сутки"),
                            ("person", "с человека"),
                            ("piece", "за шт."),
                            ("free", "бесплатно"),
                        ],
                        default="hour",
                        max_length=12,
                        verbose_name="Единица",
                    ),
                ),
                (
                    "price_note",
                    models.CharField(
                        blank=True,
                        help_text="Например: «минимум 2 часа». Точный расчёт — в виджете Контура.",
                        max_length=120,
                        verbose_name="Примечание к цене",
                    ),
                ),
                (
                    "is_hourly",
                    models.BooleanField(
                        default=False,
                        help_text="Отмечать для бани, беседки и т.п. — того, что бронируется почасово.",
                        verbose_name="Почасовой объект в Контуре",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Показывать на сайте"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Порядок"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Фото",
                    ),
                ),
            ],
            options={
                "verbose_name": "Допуслуга",
                "verbose_name_plural": "Допуслуги",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
