# Generated by Django 5.2.17 on 2026-10-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_services_copy_07_10'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='in_progress',
            field=models.BooleanField(default=False, help_text='Показать плашку «Раздел дополняется» и закрыть страницу от поисковиков, пока она не готова.', verbose_name='Раздел дополняется'),
        ),
    ]
