# Generated by Django 5.2.17 on 2026-10-07 07:53

from django.db import migrations, models

# Из постов Telegram: гости о бане (01.10.2025), беседка с печью (26.06.2026).
INCLUDES = {
    "russkaya-banya": "берёзовые и дубовые веники, травяной чай",
    "bolshaya-besedka": "русская печь, до 50 гостей",
}


def fill(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    for slug, text in INCLUDES.items():
        Service.objects.using(schema_editor.connection.alias).filter(slug=slug, includes="").update(includes=text)


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='includes',
            field=models.CharField(blank=True, help_text='Одна строка на странице услуг, например: веники и травяной чай.', max_length=160, verbose_name='Что входит'),
        ),
        migrations.RunPython(fill, migrations.RunPython.noop),
    ]
