# Generated by Django 5.2.17 on 2026-08-25 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("houses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(max_length=120, verbose_name="Имя автора"),
                ),
                ("text", models.TextField(verbose_name="Текст отзыва")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "visit_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата поездки"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("site", "Форма на сайте"),
                            ("yandex", "Яндекс.Карты"),
                            ("avito", "Авито"),
                            ("other", "Другое"),
                        ],
                        default="site",
                        max_length=16,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Отзывы публикуются только вручную после проверки.",
                        verbose_name="Опубликован",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Порядок"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлен"),
                ),
                (
                    "house",
                    models.ForeignKey(
                        blank=True,
                        help_text="Пусто — отзыв идёт только в общий пул на страницу «Отзывы».",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="houses.housepage",
                        verbose_name="Дом",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
    ]
