# Generated by Django 5.2.17 on 2026-08-27 00:55

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Вступление"
                    ),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(blank=True, verbose_name="Текст"),
                ),
            ],
            options={
                "verbose_name": "Страница «Отзывы»",
            },
            bases=("wagtailcore.page",),
        ),
    ]
