# Generated by Django 5.2.17 on 2026-10-07 07:45

from decimal import Decimal

from django.db import migrations, models

# Карточка организации на 07.10.2026: https://yandex.ru/maps/org/luchshiy_sezon/3306085141/reviews/
YANDEX = {
    "yandex_rating": Decimal("5.0"),
    "yandex_ratings_count": 67,
    "yandex_reviews_count": 55,
    "yandex_tags": "атмосфера, персонал, чистота",
    "yandex_url": "https://yandex.ru/maps/org/luchshiy_sezon/3306085141/reviews/",
}


def fill_rating(apps, schema_editor):
    ReviewsPage = apps.get_model("reviews", "ReviewsPage")
    Revision = apps.get_model("wagtailcore", "Revision")
    alias = schema_editor.connection.alias
    for page in ReviewsPage.objects.using(alias).filter(yandex_rating__isnull=True):
        ReviewsPage.objects.using(alias).filter(pk=page.pk).update(**YANDEX)
        revision = Revision.objects.using(alias).filter(pk=page.latest_revision_id).first()
        if revision and isinstance(revision.content, dict):
            content = dict(revision.content)
            content.update({k: (str(v) if isinstance(v, Decimal) else v) for k, v in YANDEX.items() if not content.get(k)})
            Revision.objects.using(alias).filter(pk=revision.pk).update(content=content)


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('reviews', '0003_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewspage',
            name='yandex_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Рейтинг на Яндекс Картах'),
        ),
        migrations.AddField(
            model_name='reviewspage',
            name='yandex_ratings_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценок'),
        ),
        migrations.AddField(
            model_name='reviewspage',
            name='yandex_reviews_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Отзывов'),
        ),
        migrations.AddField(
            model_name='reviewspage',
            name='yandex_tags',
            field=models.CharField(blank=True, help_text='Через запятую, из сводки Яндекса.', max_length=160, verbose_name='Что хвалят'),
        ),
        migrations.AddField(
            model_name='reviewspage',
            name='yandex_url',
            field=models.URLField(blank=True, verbose_name='Страница отзывов на Яндекс Картах'),
        ),
        migrations.AlterField(
            model_name='review',
            name='source',
            field=models.CharField(choices=[('site', 'Форма на сайте'), ('yandex', 'Яндекс.Карты'), ('avito', 'Авито'), ('vk', 'ВКонтакте'), ('other', 'Другое')], default='site', max_length=16, verbose_name='Источник'),
        ),
        migrations.RunPython(fill_rating, migrations.RunPython.noop),
    ]
