# Generated by Django 5.2.17 on 2026-10-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_yandex_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewspage',
            name='in_progress',
            field=models.BooleanField(default=False, help_text='Показать плашку «Раздел дополняется» и закрыть страницу от поисковиков, пока она не готова.', verbose_name='Раздел дополняется'),
        ),
    ]
