# Generated by Django 5.2.17 on 2026-08-25 12:48

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Главная страница"},
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Фото к блоку",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_text",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="Текст о ферме"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_title",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Заголовок блока о ферме"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="directions_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Страница «Как добраться»",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="directions_teaser",
            field=models.CharField(
                blank=True,
                help_text="Например: «2 часа от МКАД по Симферопольскому шоссе».",
                max_length=255,
                verbose_name="Краткий текст о дороге",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="directions_title",
            field=models.CharField(
                blank=True,
                default="Как добраться",
                max_length=120,
                verbose_name="Заголовок блока «Как добраться»",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_cta_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Обычно раздел «Наши домики».",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Куда ведёт кнопка",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_cta_text",
            field=models.CharField(
                default="Посмотреть дома", max_length=40, verbose_name="Текст кнопки"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_subtitle",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Подзаголовок"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_title",
            field=models.CharField(
                blank=True,
                help_text="Короткая надпись-описание под логотипом.",
                max_length=120,
                verbose_name="Заголовок первого экрана",
            ),
        ),
        migrations.CreateModel(
            name="HomeSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True,
                        help_text="Что на фото. Нужно для доступности и поиска.",
                        max_length=200,
                        verbose_name="Описание фото",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slides",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото слайд-шоу",
                "verbose_name_plural": "Фото слайд-шоу",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
