# Generated by Django 5.2.17 on 2026-08-26 17:17

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_homepage_options_homepage_about_image_and_more"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="about_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Куда ведёт кнопка «Подробнее» из блока о ферме.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Страница «О нас»",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="gallery_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Страница «Галерея»",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="gallery_text",
            field=models.TextField(
                blank=True, verbose_name="Текст под заголовком галереи"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="gallery_title",
            field=models.CharField(
                blank=True,
                default="Фотогалерея",
                max_length=120,
                verbose_name="Заголовок фотогалереи",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="quote_author",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Подпись под цитатой"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="quote_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Фото к цитате",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="quote_text",
            field=models.TextField(
                blank=True,
                help_text="Крупная выдержка между блоками «О нас» и «Наши домики».",
                verbose_name="Текст блока-цитаты",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="slogan",
            field=models.CharField(
                blank=True,
                help_text="Одна строка во всю ширину. По макету: «Не ждите подходящего момента…».",
                max_length=200,
                verbose_name="Слоган",
            ),
        ),
        migrations.CreateModel(
            name="HomeGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Описание фото"
                    ),
                ),
                (
                    "is_large",
                    models.BooleanField(
                        default=False,
                        help_text="Занимает две ячейки. Отмечать одну-две.",
                        verbose_name="Крупная плитка",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото галереи",
                "verbose_name_plural": "Фото галереи",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
