# Generated by Django 5.2.17 on 2026-08-26 17:40

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_homepage_about_page_homepage_gallery_page_and_more"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="nearby_more_label",
            field=models.CharField(
                blank=True,
                default="Больше интересных мест рядом",
                max_length=80,
                verbose_name="Текст кнопки под блоком «Интересное рядом»",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="nearby_more_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Куда ведёт кнопка",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="territory_lead",
            field=models.CharField(
                blank=True,
                help_text="По макету: «Большой лесной массив для уединённого отдыха».",
                max_length=200,
                verbose_name="Подпись под заголовком «Наша территория»",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="territory_more_label",
            field=models.CharField(
                blank=True,
                default="Больше развлечений и услуг",
                max_length=80,
                verbose_name="Текст плитки-ссылки в мозаике",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="territory_more_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Куда ведёт плитка-ссылка",
            ),
        ),
        migrations.CreateModel(
            name="HeroLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("label", models.CharField(max_length=60, verbose_name="Подпись")),
                (
                    "link_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="Куда ведёт",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero_links",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кнопка-раздел",
                "verbose_name_plural": "Кнопки-разделы",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
