# Generated by Django 5.2.17 on 2026-10-03 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_nearby_more_label_homepage_nearby_more_page_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_mobile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фото блока о ферме на телефоне'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mobile_photos_initialized',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_mobile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фото цитаты на телефоне'),
        ),
    ]
